# Generated by Django 2.1 on 2018-09-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='about_me',
            new_name='about_the_authors',
        ),
        migrations.AddField(
            model_name='proposal',
            name='name_of_author1',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='proposal',
            name='name_of_author2',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='proposal',
            name='terms_and_conditions',
            field=models.BooleanField(default='True'),
        ),
    ]
