# Generated by Django 2.1 on 2018-09-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180925_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='how_did_you_hear_about_us',
            field=models.CharField(blank=True, choices=[('Poster', 'Poster'), ('FOSSEE website', 'FOSSEE website'), ('Google', 'Google'), ('Social Media', 'Social Media'), ('From other College', 'From other College')], max_length=255),
        ),
    ]
